name: DAuth
version: ${version}
main: org.isnsest.dauth.DAuth
api-version: '1.21'
author: isnsest
folia-supported: true
commands:
  changepassword:
    description: Change your password
    aliases:
      - changepass
      - cpass
    usage: /changepassword
  dreload:
    description: Reload config
    permission: dauth.reload
    usage: /dreload
  2fa:
    description: 2FA
    usage: /2fa
  unregister:
    description: Unregister
    usage: /unregister
  logout:
    description: Logout
    usage: /logout